import { expect } from 'chai';
/* eslint-disable @typescript-eslint/no-explicit-any */
import * as fc from 'fast-check';
import { Database } from '../src/core/database.js';
import { compareSqlValues } from '../src/util/comparison.js';
import { safeJsonStringify } from '../src/util/serialization.js';
import type { SqlValue } from '../src/common/types.js';
import { Parser } from '../src/parser/parser.js';
import { QuereusError } from '../src/common/errors.js';

describe('Property-Based Tests', () => {
	let db: Database;

	beforeEach(() => {
		db = new Database();
		// Ensure collations are registered (already done in Database constructor)
	});

	afterEach(async () => {
		await db.close();
	});

	/**
	 * Deep equality comparison that treats -0 and +0 as equal,
	 * since JSON cannot preserve the distinction between them.
	 */
	function deepEqualIgnoringZeroSign(actual: any, expected: any): boolean {
		if (actual === expected) return true;

		// Handle the -0 vs +0 case
		if (typeof actual === 'number' && typeof expected === 'number' &&
			actual === 0 && expected === 0) {
			return true; // Treat -0 and +0 as equal
		}

		// Handle arrays
		if (Array.isArray(actual) && Array.isArray(expected)) {
			if (actual.length !== expected.length) return false;
			for (let i = 0; i < actual.length; i++) {
				if (!deepEqualIgnoringZeroSign(actual[i], expected[i])) return false;
			}
			return true;
		}

		// Handle objects
		if (actual !== null && expected !== null &&
			typeof actual === 'object' && typeof expected === 'object') {
			const actualKeys = Object.keys(actual);
			const expectedKeys = Object.keys(expected);
			if (actualKeys.length !== expectedKeys.length) return false;

			for (const key of actualKeys) {
				if (!expectedKeys.includes(key)) return false;
				if (!deepEqualIgnoringZeroSign(actual[key], expected[key])) return false;
			}
			return true;
		}

		return false;
	}

	// --- 1. Collation Comparator ---
	describe('Collation Comparator', () => {
		const collationsToTest = ['BINARY', 'NOCASE', 'RTRIM'];

		for (const collationName of collationsToTest) {
			it(`should sort consistently with compare function for ${collationName} collation`, async () => {
				await db.exec(`CREATE TABLE coll_t (id INTEGER PRIMARY KEY, txt TEXT COLLATE ${collationName}) USING memory`);

				await fc.assert(fc.asyncProperty(fc.array(fc.string(), { minLength: 1, maxLength: 20 }), async (strings) => {
					// Use a Map to handle potential duplicate strings generated by fast-check, preserving insertion order for comparison
					const uniqueStringsMap = new Map<string, boolean>();
					strings.forEach(s => uniqueStringsMap.set(s, true));
					const uniqueStrings = Array.from(uniqueStringsMap.keys());

					// Reset table for each property run
					await db.exec('DELETE FROM coll_t');
					const stmt = db.prepare('INSERT INTO coll_t (id, txt) VALUES (?, ?)');
					try {
						for (let i = 0; i < uniqueStrings.length; i++) {
							await stmt.run([i + 1, uniqueStrings[i]]);
						}
					} finally {
						await stmt.finalize();
					}

					// Get sorted results from the database
					const dbSorted: Record<string, any>[] = [];
					for await (const row of db.eval(`SELECT txt FROM coll_t ORDER BY txt`)) {
						dbSorted.push(row);
					}
					const dbSortedStrings = dbSorted.map((row: Record<string, any>) => row.txt as string);

					// Sort the original unique strings using the JavaScript compare function
					const jsSortedStrings = [...uniqueStrings].sort((a, b) => compareSqlValues(a, b, collationName));

					// Compare the two sorted lists
					expect(dbSortedStrings).to.deep.equal(jsSortedStrings, `Mismatch for collation ${collationName} with input: ${safeJsonStringify(uniqueStrings)}`);
				}), { numRuns: 50 }); // Keep numRuns reasonable for CI
			});
		}
	});

	// --- 2. Numeric Affinity ---
	describe('Numeric Affinity', () => {
		// Define an arbitrary that generates values representable as NULL, INTEGER, REAL, or TEXT that might look numeric
		const sqlValueArbitrary = fc.oneof(
			fc.constant(null),
			fc.integer(),
			fc.float({ noNaN: true }), // Exclude NaN as it complicates SQL comparisons
			fc.boolean(),
			fc.string(), // Includes numeric-looking strings
			fc.bigInt()
			// fc.uint8Array() // Skip BLOBs for numeric affinity tests
		);

		it('should compare values according to numeric affinity', async () => {
			await db.exec('CREATE TABLE num_t (id INTEGER PRIMARY KEY, v ANY null) USING memory'); // Use ANY type (has NUMERIC affinity)

			await fc.assert(fc.asyncProperty(sqlValueArbitrary, sqlValueArbitrary, async (valA, valB) => {
				// Insert values and let SQL apply type affinity conversion
				await db.exec('DELETE FROM num_t');
				// Don't reuse prepared statements - parameter types may differ between runs
				const stmt1 = db.prepare('INSERT INTO num_t (id, v) VALUES (?, ?)');
				try {
					await stmt1.run([1, valA]);
				} finally {
					await stmt1.finalize();
				}
				const stmt2 = db.prepare('INSERT INTO num_t (id, v) VALUES (?, ?)');
				try {
					await stmt2.run([2, valB]);
				} finally {
					await stmt2.finalize();
				}

				// Retrieve the actual values after type affinity conversion
				const actualValues: SqlValue[] = [];
				for await (const row of db.eval('SELECT v FROM num_t ORDER BY id')) {
					actualValues.push(row.v);
				}
				const [actualA, actualB] = actualValues;

				// For ORDER BY, we use compareSqlValues directly (no coercion)
				// ORDER BY uses storage class ordering: NULL < NUMERIC < TEXT < BLOB
				const expectedOrderByComparison = compareSqlValues(actualA, actualB, 'BINARY');

				// Test ordering behavior using ORDER BY
				const orderedValues: SqlValue[] = [];
				for await (const row of db.eval('SELECT v FROM num_t ORDER BY v')) {
					orderedValues.push(row.v);
				}

				// Check if the ordering matches our expectation based on storage class ordering
				if (expectedOrderByComparison < 0) {
					expect(orderedValues).to.deep.equal([actualA, actualB],
						`ORDER BY should place ${safeJsonStringify(actualA)} before ${safeJsonStringify(actualB)}`);
				} else if (expectedOrderByComparison > 0) {
					expect(orderedValues).to.deep.equal([actualB, actualA],
						`ORDER BY should place ${safeJsonStringify(actualB)} before ${safeJsonStringify(actualA)}`);
				} else {
					// Equal values - order doesn't matter, but both should be present
					expect(orderedValues).to.have.lengthOf(2);
					expect(orderedValues).to.include(actualA);
					expect(orderedValues).to.include(actualB);
				}

				// For non-NULL values, also test SQL boolean comparisons
				// SELECT ? = ? uses storage class ordering (no column affinity coercion)
				// NULL < INTEGER/REAL < TEXT < BLOB
				if (actualA !== null && actualB !== null) {
					const expectedComparison = compareSqlValues(actualA, actualB, 'BINARY');

					let dbComparison: number;
					try {
						// Check A = B using eval and taking the first row
						let eqResult: Record<string, any> | undefined;
						for await (const row of db.eval('SELECT ? = ? as result', [actualA, actualB])) {
							eqResult = row;
							break; // Only need the first (and only) row
						}
						if (eqResult?.result) {
							dbComparison = 0;
						} else {
							// Check A < B using eval and taking the first row
							let ltResult: Record<string, any> | undefined;
							for await (const row of db.eval('SELECT ? < ? as result', [actualA, actualB])) {
								ltResult = row;
								break; // Only need the first row
							}
							dbComparison = ltResult?.result ? -1 : 1;
						}
					} catch (e: any) {
						// If the comparison itself throws an error in SQL, fail the property test
						fc.pre(false); // Discard this run if SQL comparison fails
						throw new Error(`SQL comparison failed for (${actualA}, ${actualB}): ${e.message}`);
					}

					expect(dbComparison).to.equal(expectedComparison,
						`Mismatch for compare(${safeJsonStringify(actualA)}, ${safeJsonStringify(actualB)}). JS=${expectedComparison}, DB=${dbComparison}`
					);
				}
			}), { numRuns: 200 }); // Increase runs for more diverse value pairs
		});
	});

	// --- 3. JSON Roundtrip ---
	describe('JSON Roundtrip', () => {
		const jsonValueArbitrary = fc.jsonValue();

		it('should preserve JSON values through json() and json_extract()', async () => {
			await fc.assert(fc.asyncProperty(jsonValueArbitrary, async (originalValue) => {
				let retrievedValueParsed: any;
				try {
					let resultRow: Record<string, any> | undefined;
					for await (const row of db.eval("SELECT json_extract(json_quote(?), '$') as result", [originalValue as SqlValue])) {
						resultRow = row;
						break; // We only expect one row from this SELECT
					}

					if (resultRow) {
						retrievedValueParsed = resultRow.result;
					} else {
						// This case should ideally not be hit if originalValue is valid for json_quote
						// and json_extract can process it. If it is, it might indicate an issue
						// with how null/empty results are handled by db.eval or the underlying functions.
						// For certain inputs like trying to json_quote a function or symbol (which fc.jsonValue should not produce),
						// an error might occur during SQL execution, caught by the outer catch block.
						// If the query legitimately returns no rows (e.g. SELECT FROM empty_table), this branch would be hit.
						// But SELECT json_extract(...) should always return one row.
						throw new Error('json_extract query returned no result row unexpectedly.');
					}
				} catch (e: any) {
					fc.pre(false); // Discard this run if SQL execution fails
					throw new Error(`JSON roundtrip query failed for value ${safeJsonStringify(originalValue)}: ${e.message}`);
				}

				// Handle the different ways json_extract returns values based on SQLite compatibility:
				// - Objects/arrays: returned as JSON strings
				// - Booleans: converted to integers (1/0)
				// - Numbers/strings/null: returned as-is

				if (typeof retrievedValueParsed === 'string' && (typeof originalValue === 'object' && originalValue !== null)) {
					// Objects and arrays are returned as JSON strings - parse them for comparison
					try {
						const parsedRetrieved = JSON.parse(retrievedValueParsed);
						const isEqual = deepEqualIgnoringZeroSign(parsedRetrieved, originalValue);
						void expect(isEqual,
							`JSON roundtrip mismatch after parsing string result.\nOriginal: ${safeJsonStringify(originalValue)}\nRetrieved (raw): ${safeJsonStringify(retrievedValueParsed)}\nRetrieved (parsed): ${safeJsonStringify(parsedRetrieved)}`
						).to.be.true;
					} catch (parseError) {
						throw new Error(`JSON roundtrip failed - could not parse retrieved string.\nOriginal: ${safeJsonStringify(originalValue)}\nRetrieved: ${safeJsonStringify(retrievedValueParsed)}\nParse error: ${parseError instanceof Error ? parseError.message : String(parseError)}`);
					}
				} else if (typeof originalValue === 'boolean' && typeof retrievedValueParsed === 'number') {
					// Booleans are converted to integers by json_extract (SQLite compatibility)
					const expectedInteger = originalValue ? 1 : 0;
					void expect(retrievedValueParsed).to.equal(expectedInteger,
						`JSON boolean roundtrip mismatch.\nOriginal boolean: ${originalValue}\nExpected integer: ${expectedInteger}\nRetrieved: ${retrievedValueParsed}`
					);
				} else {
					// For other scalars (numbers, strings, null), use zero-sign-aware comparison
					const isEqual = deepEqualIgnoringZeroSign(retrievedValueParsed, originalValue);
					void expect(isEqual,
						`JSON roundtrip mismatch.\nOriginal: ${safeJsonStringify(originalValue)} (type: ${typeof originalValue})\nRetrieved: ${safeJsonStringify(retrievedValueParsed)} (type: ${typeof retrievedValueParsed})`
					).to.be.true;
				}
			}), { numRuns: 200 });
		});
	});

	// --- 4. Mixed Type Arithmetic Edge Cases ---
	describe('Mixed Type Arithmetic Edge Cases', () => {
		const complexValueArbitrary = fc.oneof(
			fc.constant(null),
			fc.integer({ min: -1000, max: 1000 }),
			fc.float({ min: -1000, max: 1000, noNaN: true }),
			fc.boolean(),
			fc.oneof(
				fc.string({ minLength: 0, maxLength: 5 }),
				fc.integer().map(n => n.toString()),
				fc.float().map(n => n.toString()),
				fc.constant(''),
				fc.constant('0'),
				fc.constant('1'),
				fc.constant('true'),
				fc.constant('false')
			)
		);

		it('should handle mixed type arithmetic consistently across contexts', async () => {
			await db.exec('CREATE TABLE mixed_test (id INTEGER PRIMARY KEY, a ANY null, b ANY null) USING memory');

			await fc.assert(fc.asyncProperty(complexValueArbitrary, complexValueArbitrary, async (valA, valB) => {
				// Clear table and insert test values
				await db.exec('DELETE FROM mixed_test');
				const stmt = db.prepare('INSERT INTO mixed_test (id, a, b) VALUES (?, ?, ?)');
				try {
					await stmt.run([1, valA, valB]);
				} finally {
					await stmt.finalize();
				}

				// Test arithmetic in different contexts - they should all produce the same result or all fail
				let selectResult: any = undefined;
				let selectFailed = false;
				let whereResult: any = undefined;
				let whereFailed = false;

				// Test in SELECT
				try {
					for await (const row of db.eval('SELECT (a + b) as result FROM mixed_test')) {
						selectResult = row.result;
						break;
					}
				} catch {
					selectFailed = true;
				}

				// Test in WHERE (using a comparison to ensure arithmetic works)
				try {
					for await (const row of db.eval('SELECT (a + b) as result FROM mixed_test WHERE (a + b) = (a + b)')) {
						whereResult = row.result;
						break;
					}
				} catch {
					whereFailed = true;
				}

				// Both should succeed or both should fail
				expect(selectFailed).to.equal(whereFailed,
					`Arithmetic behavior inconsistent between SELECT and WHERE for (${safeJsonStringify(valA)}, ${safeJsonStringify(valB)})`);

				// If both succeeded, results should match
				// Note: if selectResult is null, whereResult might be undefined (no rows returned)
				// This is expected behavior when the result is null
				if (!selectFailed && !whereFailed) {
					if (selectResult === null) {
						// If SELECT returns null, WHERE with self-comparison should return no rows (undefined)
						// This is actually correct behavior - NULL != NULL in SQL
						void expect(whereResult).to.be.undefined;
					} else {
						// For non-null results, they should match exactly
						expect(selectResult).to.equal(whereResult,
							`Arithmetic results differ between SELECT and WHERE for (${safeJsonStringify(valA)}, ${safeJsonStringify(valB)})`);
					}
				}
			}), { numRuns: 100 });
		});
	});

	// --- 5. Parser Robustness ---
	describe('Parser Robustness', () => {
		it('should never throw unhandled exceptions on random input', () => {
			const parser = new Parser();

			fc.assert(fc.property(fc.string({ minLength: 0, maxLength: 200 }), (input) => {
				try {
					parser.parseAll(input);
				} catch (e) {
					if (!(e instanceof QuereusError)) {
						throw new Error(`Parser threw non-QuereusError on input ${safeJsonStringify(input)}: ${e}`);
					}
				}
			}), { numRuns: 200 });
		});

		it('should handle SQL-like fragments mixed with garbage', () => {
			const parser = new Parser();
			const sqlFragments = fc.oneof(
				fc.constant('select'),
				fc.constant('from'),
				fc.constant('where'),
				fc.constant('insert'),
				fc.constant('into'),
				fc.constant('values'),
				fc.constant('update'),
				fc.constant('delete'),
				fc.constant('create'),
				fc.constant('table'),
				fc.constant('drop'),
				fc.constant('alter'),
				fc.constant('join'),
				fc.constant('on'),
				fc.constant('group by'),
				fc.constant('order by'),
				fc.constant('having'),
				fc.constant('limit'),
				fc.constant('('),
				fc.constant(')'),
				fc.constant(','),
				fc.constant(';'),
				fc.constant('*'),
				fc.constant('='),
				fc.constant('and'),
				fc.constant('or'),
				fc.constant('not'),
				fc.string({ minLength: 1, maxLength: 10 })
			);

			fc.assert(fc.property(fc.array(sqlFragments, { minLength: 1, maxLength: 15 }), (fragments) => {
				const input = fragments.join(' ');
				try {
					parser.parseAll(input);
				} catch (e) {
					if (!(e instanceof QuereusError)) {
						throw new Error(`Parser threw non-QuereusError on SQL fragment input: ${e}`);
					}
				}
			}), { numRuns: 200 });
		});

		it('should handle random identifiers in SELECT statements gracefully', () => {
			const parser = new Parser();
			const identArbitrary = fc.oneof(
				fc.stringMatching(/^[a-zA-Z_][a-zA-Z0-9_]{0,20}$/),
				// Bracket-quoted identifiers
				fc.string({ minLength: 1, maxLength: 20 }).map(s => `[${s.replace(/]/g, ']]')}]`),
				// Double-quote identifiers
				fc.string({ minLength: 1, maxLength: 20 }).map(s => `"${s.replace(/"/g, '""')}"`),
				// Backtick identifiers
				fc.string({ minLength: 1, maxLength: 20 }).map(s => '`' + s.replace(/`/g, '``') + '`'),
				// Reserved words used as identifiers
				fc.constantFrom('select', 'from', 'where', 'table', 'index', 'order', 'group', 'having', 'limit', 'null', 'true', 'false')
			);

			fc.assert(fc.property(identArbitrary, (ident) => {
				const sql = `select ${ident} from t`;
				try {
					parser.parseAll(sql);
				} catch (e) {
					if (!(e instanceof QuereusError)) {
						throw new Error(`Parser threw non-QuereusError on identifier ${safeJsonStringify(ident)}: ${e}`);
					}
				}
			}), { numRuns: 200 });
		});
	});

	// --- 6. Expression Evaluation Consistency ---
	describe('Expression Evaluation Consistency', () => {
		// Build random arithmetic expression trees
		const literalArb = fc.integer({ min: -100, max: 100 });
		const opArb = fc.constantFrom('+', '-', '*');

		// Generate expression as [sqlString, jsValue] pairs
		// Avoid division to keep things simple (division-by-zero, integer vs float semantics)
		// Negative literals are wrapped in parens so the parser doesn't see e.g. `* -1`
		function litToSql(n: number): string {
			return n < 0 ? `(${n})` : String(n);
		}

		function exprArbitrary(depth: number): fc.Arbitrary<{ sql: string; value: number }> {
			if (depth <= 0) {
				return literalArb.map(n => ({ sql: litToSql(n), value: n }));
			}
			return fc.oneof(
				literalArb.map(n => ({ sql: litToSql(n), value: n })),
				fc.tuple(exprArbitrary(depth - 1), opArb, exprArbitrary(depth - 1)).map(([left, op, right]) => {
					let value: number;
					switch (op) {
						case '+': value = left.value + right.value; break;
						case '-': value = left.value - right.value; break;
						case '*': value = left.value * right.value; break;
						default: value = left.value + right.value;
					}
					return { sql: `(${left.sql} ${op} ${right.sql})`, value };
				})
			);
		}

		it('should evaluate arithmetic expressions consistently with JS', async () => {
			await fc.assert(fc.asyncProperty(exprArbitrary(3), async (expr) => {
				// Skip expressions that would overflow JS safe integers
				fc.pre(Math.abs(expr.value) < Number.MAX_SAFE_INTEGER);

				let result: any;
				for await (const row of db.eval(`select ${expr.sql} as r`)) {
					result = row.r;
					break;
				}

				expect(result).to.equal(expr.value,
					`Mismatch for expression: ${expr.sql}, expected ${expr.value}, got ${result}`);
			}), { numRuns: 200 });
		});

		it('should evaluate boolean comparison expressions consistently', async () => {
			const compOp = fc.constantFrom('=', '!=', '<', '>', '<=', '>=');

			await fc.assert(fc.asyncProperty(literalArb, compOp, literalArb, async (a, op, b) => {
				let jsResult: boolean;
				switch (op) {
					case '=': jsResult = a === b; break;
					case '!=': jsResult = a !== b; break;
					case '<': jsResult = a < b; break;
					case '>': jsResult = a > b; break;
					case '<=': jsResult = a <= b; break;
					case '>=': jsResult = a >= b; break;
					default: jsResult = false;
				}

				let sqlResult: any;
				for await (const row of db.eval(`select (${litToSql(a)} ${op} ${litToSql(b)}) as r`)) {
					sqlResult = row.r;
					break;
				}

				// SQL may return boolean true/false or 1/0
				const sqlBool = sqlResult === true || sqlResult === 1;
				expect(sqlBool).to.equal(jsResult,
					`Mismatch for ${a} ${op} ${b}: SQL=${sqlResult}, JS=${jsResult}`);
			}), { numRuns: 200 });
		});
	});

	// --- 7. Comparison Transitivity and Antisymmetry ---
	describe('Comparison Properties', () => {
		const mixedValueArb = fc.oneof(
			fc.constant(null as SqlValue),
			fc.integer({ min: -1000, max: 1000 }) as fc.Arbitrary<SqlValue>,
			fc.float({ min: -1000, max: 1000, noNaN: true, noDefaultInfinity: true }) as fc.Arbitrary<SqlValue>,
			fc.string({ minLength: 0, maxLength: 10 }) as fc.Arbitrary<SqlValue>,
			fc.boolean() as fc.Arbitrary<SqlValue>
		);

		it('should maintain antisymmetry: compare(a,b) === -compare(b,a)', () => {
			fc.assert(fc.property(mixedValueArb, mixedValueArb, (a, b) => {
				const ab = compareSqlValues(a, b);
				const ba = compareSqlValues(b, a);
				expect(Math.sign(ab)).to.equal(-Math.sign(ba),
					`Antisymmetry violated: compare(${safeJsonStringify(a)}, ${safeJsonStringify(b)})=${ab}, compare(${safeJsonStringify(b)}, ${safeJsonStringify(a)})=${ba}`);
			}), { numRuns: 200 });
		});

		it('should maintain reflexivity: compare(a,a) === 0', () => {
			fc.assert(fc.property(mixedValueArb, (a) => {
				expect(compareSqlValues(a, a)).to.equal(0,
					`Reflexivity violated for ${safeJsonStringify(a)}`);
			}), { numRuns: 200 });
		});

		it('should maintain transitivity: if a<=b and b<=c then a<=c', () => {
			fc.assert(fc.property(mixedValueArb, mixedValueArb, mixedValueArb, (a, b, c) => {
				const ab = compareSqlValues(a, b);
				const bc = compareSqlValues(b, c);
				const ac = compareSqlValues(a, c);

				if (ab <= 0 && bc <= 0) {
					expect(ac).to.be.at.most(0,
						`Transitivity violated: ${safeJsonStringify(a)} <= ${safeJsonStringify(b)} <= ${safeJsonStringify(c)}, but compare(a,c)=${ac}`);
				}
				if (ab >= 0 && bc >= 0) {
					expect(ac).to.be.at.least(0,
						`Transitivity violated: ${safeJsonStringify(a)} >= ${safeJsonStringify(b)} >= ${safeJsonStringify(c)}, but compare(a,c)=${ac}`);
				}
			}), { numRuns: 200 });
		});
	});

	// --- 8. Insert/Select Roundtrip ---
	describe('Insert/Select Roundtrip', () => {
		it('should roundtrip INTEGER values', async () => {
			await db.exec('CREATE TABLE rt_int (id INTEGER PRIMARY KEY, v INTEGER) USING memory');

			await fc.assert(fc.asyncProperty(fc.integer(), async (val) => {
				await db.exec('DELETE FROM rt_int');
				const stmt = db.prepare('INSERT INTO rt_int (id, v) VALUES (1, ?)');
				try { await stmt.run([val]); } finally { await stmt.finalize(); }

				for await (const row of db.eval('SELECT v FROM rt_int')) {
					expect(row.v).to.equal(val);
				}
			}), { numRuns: 100 });
		});

		it('should roundtrip REAL values', async () => {
			await db.exec('CREATE TABLE rt_real (id INTEGER PRIMARY KEY, v REAL) USING memory');

			await fc.assert(fc.asyncProperty(fc.float({ noNaN: true, noDefaultInfinity: true }), async (val) => {
				await db.exec('DELETE FROM rt_real');
				const stmt = db.prepare('INSERT INTO rt_real (id, v) VALUES (1, ?)');
				try { await stmt.run([val]); } finally { await stmt.finalize(); }

				for await (const row of db.eval('SELECT v FROM rt_real')) {
					// Account for -0 vs +0
					if (val === 0 && row.v === 0) return;
					expect(row.v).to.equal(val);
				}
			}), { numRuns: 100 });
		});

		it('should roundtrip TEXT values', async () => {
			await db.exec('CREATE TABLE rt_text (id INTEGER PRIMARY KEY, v TEXT) USING memory');

			await fc.assert(fc.asyncProperty(fc.string({ minLength: 0, maxLength: 100 }), async (val) => {
				await db.exec('DELETE FROM rt_text');
				const stmt = db.prepare('INSERT INTO rt_text (id, v) VALUES (1, ?)');
				try { await stmt.run([val]); } finally { await stmt.finalize(); }

				for await (const row of db.eval('SELECT v FROM rt_text')) {
					expect(row.v).to.equal(val);
				}
			}), { numRuns: 100 });
		});

		it('should roundtrip BLOB values', async () => {
			await db.exec('CREATE TABLE rt_blob (id INTEGER PRIMARY KEY, v BLOB) USING memory');

			await fc.assert(fc.asyncProperty(fc.uint8Array({ minLength: 0, maxLength: 100 }), async (val) => {
				await db.exec('DELETE FROM rt_blob');
				const stmt = db.prepare('INSERT INTO rt_blob (id, v) VALUES (1, ?)');
				try { await stmt.run([val]); } finally { await stmt.finalize(); }

				for await (const row of db.eval('SELECT v FROM rt_blob')) {
					expect(row.v).to.deep.equal(val);
				}
			}), { numRuns: 100 });
		});

		it('should roundtrip ANY column values exactly', async () => {
			await db.exec('CREATE TABLE rt_any (id INTEGER PRIMARY KEY, v ANY null) USING memory');

			const anyValueArb = fc.oneof(
				fc.constant(null),
				fc.integer(),
				fc.float({ noNaN: true, noDefaultInfinity: true }),
				fc.string({ minLength: 0, maxLength: 50 }),
				fc.boolean()
			);

			await fc.assert(fc.asyncProperty(anyValueArb, async (val) => {
				await db.exec('DELETE FROM rt_any');
				const stmt = db.prepare('INSERT INTO rt_any (id, v) VALUES (1, ?)');
				try { await stmt.run([val]); } finally { await stmt.finalize(); }

				for await (const row of db.eval('SELECT v FROM rt_any')) {
					if (val === null) {
						expect(row.v).to.be.null;
					} else if (typeof val === 'number' && val === 0) {
						// Account for -0 vs +0
						expect(row.v).to.equal(0);
					} else {
						expect(row.v).to.equal(val);
					}
				}
			}), { numRuns: 100 });
		});
	});

	// --- 9. Temporal Roundtrip ---
	describe('Temporal Roundtrip', () => {
		it('should roundtrip DATE values through date(text(date))', async () => {
			// Generate valid year/month/day combinations
			const dateArb = fc.tuple(
				fc.integer({ min: 1970, max: 2100 }),
				fc.integer({ min: 1, max: 12 }),
				fc.integer({ min: 1, max: 28 }) // Use 28 to avoid month-length issues
			).map(([y, m, d]) => `${y}-${String(m).padStart(2, '0')}-${String(d).padStart(2, '0')}`);

			await fc.assert(fc.asyncProperty(dateArb, async (dateStr) => {
				let result: any;
				for await (const row of db.eval(`select date('${dateStr}') as r`)) {
					result = row.r;
					break;
				}
				// date() should return the same normalized ISO date
				expect(result).to.equal(dateStr,
					`DATE roundtrip failed for ${dateStr}: got ${result}`);
			}), { numRuns: 100 });
		});

		it('should roundtrip TIME values through time(text)', async () => {
			const timeArb = fc.tuple(
				fc.integer({ min: 0, max: 23 }),
				fc.integer({ min: 0, max: 59 }),
				fc.integer({ min: 0, max: 59 })
			).map(([h, m, s]) =>
				`${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
			);

			await fc.assert(fc.asyncProperty(timeArb, async (timeStr) => {
				let result: any;
				for await (const row of db.eval(`select time('${timeStr}') as r`)) {
					result = row.r;
					break;
				}
				expect(result).to.equal(timeStr,
					`TIME roundtrip failed for ${timeStr}: got ${result}`);
			}), { numRuns: 100 });
		});
	});

	// --- 10. Conversion Idempotency ---
	describe('Conversion Idempotency', () => {
		it('integer(integer(x)) = integer(x) for valid integers', async () => {
			await fc.assert(fc.asyncProperty(fc.integer({ min: -1000000, max: 1000000 }), async (val) => {
				let single: any;
				for await (const row of db.eval(`select integer(${val}) as r`)) {
					single = row.r;
					break;
				}
				let double: any;
				for await (const row of db.eval(`select integer(integer(${val})) as r`)) {
					double = row.r;
					break;
				}
				expect(double).to.equal(single,
					`Idempotency violated: integer(integer(${val})) = ${double}, integer(${val}) = ${single}`);
			}), { numRuns: 100 });
		});

		it('real(real(x)) = real(x) for valid reals', async () => {
			await fc.assert(fc.asyncProperty(
				fc.float({ min: -1000, max: 1000, noNaN: true, noDefaultInfinity: true }),
				async (val) => {
					let single: any;
					for await (const row of db.eval(`select real(${val}) as r`)) {
						single = row.r;
						break;
					}
					let double: any;
					for await (const row of db.eval(`select real(real(${val})) as r`)) {
						double = row.r;
						break;
					}
					if (single === null) {
						expect(double).to.be.null;
					} else if (typeof single === 'number' && single === 0) {
						expect(double).to.equal(0);
					} else {
						expect(double).to.equal(single,
							`Idempotency violated: real(real(${val})) = ${double}, real(${val}) = ${single}`);
					}
				}
			), { numRuns: 100 });
		});

		it('text(text(x)) = text(x) for strings', async () => {
			await fc.assert(fc.asyncProperty(
				fc.string({ minLength: 0, maxLength: 50 }),
				async (val) => {
					// Use parameterized query to avoid SQL injection issues with special chars
					let single: any;
					for await (const row of db.eval('select text(?) as r', [val])) {
						single = row.r;
						break;
					}
					let double: any;
					for await (const row of db.eval('select text(text(?)) as r', [val])) {
						double = row.r;
						break;
					}
					expect(double).to.equal(single,
						`Idempotency violated for text('${val}')`);
				}
			), { numRuns: 100 });
		});
	});

	// --- 11. Transaction Isolation ---
	describe('Transaction Isolation', () => {
		it('should never see partial transaction state via read after commit', async () => {
			await db.exec('CREATE TABLE iso_t (id INTEGER PRIMARY KEY, val INTEGER) USING memory');

			// Seed initial rows
			for (let i = 1; i <= 5; i++) {
				await db.exec(`INSERT INTO iso_t VALUES (${i}, ${i * 10})`);
			}

			await fc.assert(fc.asyncProperty(
				// Generate a random set of mutations per transaction
				fc.array(fc.tuple(
					fc.constantFrom('insert', 'update', 'delete'),
					fc.integer({ min: 1, max: 20 }),
					fc.integer({ min: 0, max: 100 }),
				), { minLength: 1, maxLength: 5 }),
				async (mutations) => {
					// Start explicit transaction
					await db.exec('BEGIN');

					try {
						for (const [op, id, val] of mutations) {
							try {
								if (op === 'insert') {
									await db.exec(`INSERT OR IGNORE INTO iso_t VALUES (${id}, ${val})`);
								} else if (op === 'update') {
									await db.exec(`UPDATE iso_t SET val = ${val} WHERE id = ${id}`);
								} else {
									await db.exec(`DELETE FROM iso_t WHERE id = ${id}`);
								}
							} catch {
								// Constraint violations are expected — continue
							}
						}
					} finally {
						await db.exec('ROLLBACK');
					}

					// After rollback, all rows should match their original values
					const rows: Array<{ id: number; val: number }> = [];
					for await (const row of db.eval('SELECT id, val FROM iso_t ORDER BY id')) {
						rows.push(row as { id: number; val: number });
					}

					// Exactly the original 5 rows with original values
					expect(rows).to.have.length(5);
					for (const row of rows) {
						expect(row.val).to.equal(row.id * 10,
							`Row ${row.id} has wrong value after rollback: expected ${row.id * 10}, got ${row.val}`);
					}
				}
			), { numRuns: 50 });
		});

		it('should preserve schema DDL through rollback', async () => {
			await fc.assert(fc.asyncProperty(
				fc.integer({ min: 1, max: 100 }),
				async (tableId) => {
					const tableName = `ddl_test_${tableId}`;

					// Ensure clean state
					await db.exec(`DROP TABLE IF EXISTS ${tableName}`);

					// Create in committed context
					await db.exec(`CREATE TABLE ${tableName} (id INTEGER PRIMARY KEY, val TEXT)`);

					// Start transaction, insert data, rollback
					await db.exec('BEGIN');
					try {
						await db.exec(`INSERT INTO ${tableName} VALUES (1, 'test')`);
					} finally {
						await db.exec('ROLLBACK');
					}

					// Table should still exist but be empty
					const rows: unknown[] = [];
					for await (const row of db.eval(`SELECT * FROM ${tableName}`)) {
						rows.push(row);
					}
					expect(rows).to.have.length(0);

					// Cleanup
					await db.exec(`DROP TABLE ${tableName}`);
				}
			), { numRuns: 20 });
		});
	});

	// --- 12. ORDER BY Stability ---
	describe('ORDER BY Stability', () => {
		it('should produce identical results for repeated ORDER BY on same data', async () => {
			await db.exec('CREATE TABLE stab_t (id INTEGER PRIMARY KEY, sort_key INTEGER, payload TEXT) USING memory');

			await fc.assert(fc.asyncProperty(
				fc.array(fc.tuple(fc.integer({ min: 1, max: 5 }), fc.string({ minLength: 1, maxLength: 10 })), { minLength: 2, maxLength: 20 }),
				async (rows) => {
					await db.exec('DELETE FROM stab_t');
					const stmt = db.prepare('INSERT INTO stab_t (id, sort_key, payload) VALUES (?, ?, ?)');
					try {
						for (let i = 0; i < rows.length; i++) {
							await stmt.run([i + 1, rows[i][0], rows[i][1]]);
						}
					} finally {
						await stmt.finalize();
					}

					// Run ORDER BY twice
					const run1: any[] = [];
					for await (const row of db.eval('SELECT id, sort_key, payload FROM stab_t ORDER BY sort_key, id')) {
						run1.push(row);
					}

					const run2: any[] = [];
					for await (const row of db.eval('SELECT id, sort_key, payload FROM stab_t ORDER BY sort_key, id')) {
						run2.push(row);
					}

					expect(run1).to.deep.equal(run2, 'ORDER BY should produce identical results across repeated executions');
				}
			), { numRuns: 100 });
		});
	});

});
